version: "3.8"

services:
  wordpress:
    build: "./services/wordpress"
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - "./.env:/var/www/html/.env"
      - "./auth.json:/var/www/html/auth.json"
      - "./services/wordpress/composer.json:/var/www/html/composer.json"
      - "./${THEME_NAME}:/var/www/html/wp-content/themes/${THEME_NAME}"
    environment:
      IS_DEVELOPMENT: 1
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_NO_INTERACTION: 1
      WORDPRESS_DEBUG: 1
      WORDPRESS_THEME_NAME: "${THEME_NAME}"
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PORT: 3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    env_file:
      - ./.env

  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  wordpress:
  db:
